config/routes.rb
Rails.application.routes.draw do
  # root 'sessions#index'    
  devise_for :users
  root 'static_pages#index'

  get '/sites', to:'static_pages#index'
  get '/users', to: 'static_pages#index'
  get '/users', to: 'static_pages#index'
  get '/users/:id', to: 'static_pages#index'
  get '/new_log', to: 'dives#new_log'
  
  resources :sessions, only: [:new]
  
  namespace :api do
    namespace :v1 do 
      resources :sites, only: [:index, :show, :create, :new]
      resources :users, only: [:index, :show]
    end 
  end 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dive.rb
class Dive < ApplicationRecord
  validates :style, presence: true, length: { minimum: 3 }
  validates :number, presence: true
  validates :depth, presence: true
  validates :visibility, presence: true
  validates :tempurature, presence: true
  validates :longitude, presence: true
  validates :latitude, presence: true
  validates :dive_buddy, presence: true

  belongs_to :site
  has_many :users, through: :excurion
end

app/models/excursion.rb
class Excursion < ApplicationRecord
  belongs_to :users
  belongs_to :dive
end

app/models/site.rb
class Site < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :region, presence: true
  validates :longitude, presence: true
  validates :latitude, presence: true

  has_many :dives
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :gender, presence: true
  validates :diving_since, presence: true

  has_many :excursions
  has_many :dives, through: :excurions
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/divers_controller.rb
class Api::V1::DiversController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }
  
  def index
    divers= Diver.all
  end

  def show
    render json: Diver.where(diverId: params["diver_Id"])
  end

  def create
    new_log = Log.new(log_params)
    log = Log.find(params[:userId])
    new_log.user = user
    if new_log.save
      render json: new_log
    else
      render json: new_log.errors
    end 
  end

  private 
  def log_params
    params.require(:log).permit(:style, :number, :depth, :visibility, :longitude, :latitude, :divebuddy, :site)
  end
end

app/controllers/api/v1/site_controller.rb
class Api::V1::SitesController < ApplicationController
  def index
    render json: Site.all
  end
end

app/controllers/api/v1/sites_controller.rb
class Api::V1::SitesController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }

  def index
    render json: Site.all
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  protect_from_forgery unless: -> { request.format.json? }
  
  def index
    render json: User.all
  end

  def show
    user = User.where(user: current_user)
    render json: user
  end

  def create
    new_log = Dive.new(dive_params)
    log = Dive.find(params[:userId])
    new_log.user = user
    if new_log.save
      render json: User.where(user: current_user) && new_log
    else
      render json: new_log.errors
    end 
  end

  private 
  def dive_params
    params.require(:dive).permit(:style, :number, :depth, :visibility, :longitude, :latitude, :divebuddy, :site)
  end
end

app/controllers/application_controller.rb
# class ApplicationController < ActionController::Base
#   # Prevent CSRF attacks by raising an exception.
#   # For APIs, you may want to use :null_session instead.
#   protect_from_forgery with: :exception
# end

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

 protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :gender, :address, :diving_since, :email])
 end
end

app/controllers/dives_controller.rb
class DivesController <ApplicationController
 
  def new
    created_log = Dive.new(current_user)
    created_log.generate_new_log
    redirect_to "/dives/#{created_log.dive.id}"
  end

  def show
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
  end
  
  def new
    render :'/homes/index'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    render :'/devise/sessions/new'
  end
  
  def new
    render :'/devise/sessions/new'
  end
end

app/controllers/sites_controller.rb
class SitesController <ApplicationController
  def index
    @sites = Site.all
  end
  def show
    @sites = Site.all
  end
  def new
    @sites = Site.new
  end

  def create
    @site = Site.new(site_params)
  end
  
  def site_params
    params.require(:site).permit(:name, :address, :region, :longitude, :latitude, :description, :image)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
  end
  
  def new
    render :'/static_pages/index'
  end
end

app/views/dives/index.html.erb
<h1>How was the Dive</h1>

app/views/homes/index.html.erb
<div id="app">

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DiveLog</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Bowlby+One+SC&display=swap&subset=latin-ext" rel="stylesheet">
</head>
<body>

  <nav class="top-bar">
    <h1><a href="/">Dive Log</a></h1>

        <center>
        <%- if current_user -%>
        <%= link_to 'My Profile', edit_user_registration_path, class: "signup-link", method: :get %> | <%= link_to 'Sign Out', destroy_user_session_path, class: "signup-link", method: :delete %>

        <%- else -%>
        <%= link_to 'Sign Up', new_user_registration_path %> |
        <%= link_to 'Sign In', new_user_session_path %>
        <%- end -%>
        </center>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>

  <%- if Rails.env.development? || Rails.env.test? -%>
    <%= javascript_tag do %>
      window.railsEnv = '<%= Rails.env %>'
    <%- end -%>
  <%- end -%>
  <%= javascript_pack_tag 'application' %>

  <%= yield :extra_footer %>
</body>
</html>

app/views/sites/index.html.erb
<div class='site-container'>
  <div class='page-content'>
    <h1>"We dive not to escape life but for life not to escape us"</h1>
    <div class='inner-content'>
      <div class='left-content'>
        <a href="/dives">Dive Details</a>
        <br>
        <% @sites.each do |site| %>
        <%= link_to "#{site.name}", sites_path(site) %>
        <% end %>
      </div>
      <div className='right-content'>
      </div>
    </div>
  </div>
</div>

app/views/sites/new.html.erb
<h1>So you have a dive site for us huh?</h1>

app/views/sites/show.html.erb
<div>
  <center>
<% @sites.each do |site| %>
<br>

<img src=<%= site.image %> width="700" height="500">
<br>
<%= site.name %>
<br>
<%= site.address %>
<br>
<%= site.region %>
<br>
<%= site.longitude %>
<br>
<%= site.latitude %>
<br>
<%= site.description %>

<% end %>
 </center>
</div>

app/views/static_pages/index.html.erb
<div id="app">
</div>